### ISSUE TITLE
multiple es6 bundles and happened.js not being triggered. Possible issue?

### ISSUE THREAD

**Issue by alex-roger-1942** [grassator/happened#2]
Hi,

I'm really loving this library :) . I have a possible issue when running happened.js in multiple contexts.

I create two react apps. which result in bundle1.js and bundle2.js. I have an npm package I export into both as follows:

```
module.exports = require('happened').create({
    scheduler: setImmediate
});
```

This works great if the two react apps don't talk to each other eg.

App2.bundle.js
```
import Bus from './bus';

class App extends Component {
  componentDidMount() {
    Bus.on('disco', () => {
      alert('dance');
    });
  }

  render() {
    return (
      <div>
        Loaded Raiser Component 
        <p>
          Try <button onClick={ () => { window.bus.trigger('disco'); } }>Raise an event locally</button>
        </p>
        <p>
          Try <button onClick={ () => { window.bus.trigger('ext'); } }>Raise an event across fragments</button>
        </p>
      </div>
    );
  }
}
export default hot(module)(App);
```
 and

App2.bundle.js
```
import React, { Component } from 'react';
import { hot } from 'react-hot-loader';
import Bus from './bus';

class App extends Component {
  componentDidMount() {
    Bus.on('ext', () => {
      alert('raised inside error');
    });

    alert(Bus.ALL_EVENTS);
  }

  render() {
    return (
      <div>Loaded Error Component with an event called error
        Try <button onClick={ () => { window.bus.trigger('disco'); } }>Raise an event from error</button>
      </div>
    );
  }
}

export default hot(module)(App);
```

from App1 I cannot trigger disco and from App2 I cannot trigger ext, but App2 can fire off disco just fine  internally but not ext. Essentially the two bundles can't communicate. I checked in both that they are being registered and if I add the Bus to the window object it works.

Inside each app componentdidmount
```
    if(!window.bus) {
      window.bus = Bus;
    }
```

Following the README it mentions just adding it as an export. I might be missing something?

This awesome library would be great as a tool for helping my microspas talk to each other.

**Comment by grassator** [comment]
To include the same bus in 2 (or more) apps you can do a couple things:

### Option 1

Add it to a global object, and then either take it directly from `window` or use [Provide Plugin](https://webpack.js.org/plugins/provide-plugin/0) to map the module to a window global. In this case you either have to make sure that the bus is only initialized once or for example inline it in the head of the page (which could be OK considering that size is quite small)

### Option 2

Use [Commons Chunk Plugin](https://webpack.js.org/plugins/commons-chunk-plugin/) and then use that chunk with the bus from both apps

**Comment by alex-roger-1942** [comment]
Ah, that makes perfect sense, I added it to the window object above and understand your rationale. Forgive my confusion, I thought wrapping in an export would make it a global.

Thank you very much. Great project.
